<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Document</title>
</head>
<body>


<form action="home" method="POST">
    <input name="dia" type="text" required placeholder="Día (ej. 2024-10-23)">
    <input name="id_evento" type="text" required placeholder="ID del Evento">
    <button type="submit">Enviar</button>
</form>
</body>
</html>