<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Document</title>
</head>
<body>
    


    <?php require_once 'templates/formVentas.phtml' ?>

    <?php foreach($ventas as $venta): ?>
        <li>Total: <?= $venta->cant_entra * $evento->precio; ?></li>
    <?php endforeach; ?>

    
</body>
</html>